# -*- coding: utf-8 -*-
"""1072번 게임.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h8OK_ctZa1JPTpHzPnJ4sI5Xi55EevCj
"""

import math 
x, y = map(int, input().split())
# 주의1 : 나누고 100을 곱하는 것과 100을 곱하고 나누는 것의 값이 다름  
before = math.trunc((100*y/x)) 

# 주의2 : 단순하게 for문으로 돌리면 e가 커서 시간 복잡도가 큼 -> 이분탐색으로 계산 
s, e = 1, 1000000000
while s < e: 
    m = (s+e)//2
    after = math.trunc((100*(y+m)/(x+m)))
    if before >= after: 
        s = m + 1
    else: 
        e = m 
after = math.trunc((100*(y+e)/(x+e)))
print(e if after > before else -1)